### Curso Formação Cientista de Dados - Fernando Amaral
#### Redes Neurais Artificiais com Keras

In [1]:
# Importação das bibliotecas
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np

In [2]:
# Carregamento da base de dados e criação dos previsores (variáveis independentes - X) e da classe (variável dependente - y)
base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
# Transformação da classe para o formato "dummy", pois temos uma rede neural com 3 neurônios na camada de saída
classe_dummy = np_utils.to_categorical(classe)
classe_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [5]:
# Divisão da base de dados entre treinamento e teste (30% para testar e 70% para treinar)
X_treino, X_teste, y_treino, y_teste = train_test_split(previsores, classe_dummy, test_size=0.3, random_state=0)

In [6]:
# Criação da estrutura da rede neural com a classe Sequential (sequência de camadas)
modelo = Sequential()

# Primeira camada oculta, 5 neurônios, 4 neurônios de entrada
modelo.add(Dense(units=5, input_dim=4))

# Segunda camada oculta
modelo.add(Dense(units=4))

# Função softmax porque temos um problema de classificação com mais de duas classes (é gerada uma probabilidade em cada neurônio)
modelo.add(Dense(units=3, activation='softmax'))

In [7]:
# Visualização da estrutura da rede neural
modelo.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 25        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [8]:
# Configuração dos parâmetros da rede neural (adam = algoritmo para atualizar os pesos e loss = cálculo do erro)
modelo.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data)
modelo.fit(X_treino, y_treino, epochs=1000, validation_data=(X_teste, y_teste))

Epoch 1/1000
4/4 [==============================] - 0s 43ms/step - loss: 3.2417 - accuracy: 0.2857 - val_loss: 2.6535 - val_accuracy: 0.3556
Epoch 2/1000
4/4 [==============================] - 0s 6ms/step - loss: 3.0831 - accuracy: 0.2857 - val_loss: 2.5490 - val_accuracy: 0.3111
Epoch 3/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.9424 - accuracy: 0.2571 - val_loss: 2.4482 - val_accuracy: 0.2667
Epoch 4/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.7945 - accuracy: 0.2286 - val_loss: 2.3528 - val_accuracy: 0.2000
Epoch 5/1000
4/4 [==============================] - 0s 8ms/step - loss: 2.6542 - accuracy: 0.2000 - val_loss: 2.2629 - val_accuracy: 0.1778
Epoch 6/1000
4/4 [==============================] - 0s 6ms/step - loss: 2.5309 - accuracy: 0.2000 - val_loss: 2.1758 - val_accuracy: 0.1556
Epoch 7/1000
4/4 [==============================] - 0s 7ms/step - loss: 2.4078 - accuracy: 0.1238 - val_loss: 2.0926 - val_accuracy: 0.1111
Epoch 8/1000
4/4 [=

In [9]:
# Previsões e mudar a variável para True ou False de acordo com o threshold 0.5
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [Fa

In [10]:
# Como é um problema com três saídas, precisamos buscar a posição que possui o maior valor (são retornados 3 valores)
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

In [11]:
# Geração da matriz de confusão
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
confusao

array([[16,  0,  0],
       [ 0, 16,  2],
       [ 0,  0, 11]], dtype=int64)

In [12]:
# Taxa de acerto
from sklearn.metrics import accuracy_score

taxa_acerto = accuracy_score(y_teste, previsoes) * 100
print(f'Taxa de acerto: {taxa_acerto:.2f}%')

Taxa de acerto: 95.56%
